version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
       - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - reviewsDB:/data/db
    ports:
      - "27017:27017"
volumes:
    reviewsDB: