version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    image: djian001/reviews
    ports:
      - "80:3001"
    links:
       - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/db
    ports:
      - "27017:27017"